// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBfgMUDlsSmn9tWFf_dtCdS1GM3UKIt1Go',
    appId: '1:239056007523:web:2a91586ab7ed9fe3d72356',
    messagingSenderId: '239056007523',
    projectId: 'hoofhub-4f4a7',
    authDomain: 'hoofhub-4f4a7.firebaseapp.com',
    storageBucket: 'hoofhub-4f4a7.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC7KGnkrP5BNY9Ik-Drl7l8wfjf7m28wxI',
    appId: '1:239056007523:android:b412c3913f2cfe84d72356',
    messagingSenderId: '239056007523',
    projectId: 'hoofhub-4f4a7',
    storageBucket: 'hoofhub-4f4a7.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDI0LElHg5mw1h912rncaClgS-XZHhA7tU',
    appId: '1:239056007523:ios:de9711abd7edef09d72356',
    messagingSenderId: '239056007523',
    projectId: 'hoofhub-4f4a7',
    storageBucket: 'hoofhub-4f4a7.firebasestorage.app',
    iosClientId: '239056007523-cpv07qk1c2a65jk2p72oqt0vk4eqqe86.apps.googleusercontent.com',
    iosBundleId: 'com.example.frontend',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDI0LElHg5mw1h912rncaClgS-XZHhA7tU',
    appId: '1:239056007523:ios:de9711abd7edef09d72356',
    messagingSenderId: '239056007523',
    projectId: 'hoofhub-4f4a7',
    storageBucket: 'hoofhub-4f4a7.firebasestorage.app',
    iosClientId: '239056007523-cpv07qk1c2a65jk2p72oqt0vk4eqqe86.apps.googleusercontent.com',
    iosBundleId: 'com.example.frontend',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBfgMUDlsSmn9tWFf_dtCdS1GM3UKIt1Go',
    appId: '1:239056007523:web:7a40f6ef475dadced72356',
    messagingSenderId: '239056007523',
    projectId: 'hoofhub-4f4a7',
    authDomain: 'hoofhub-4f4a7.firebaseapp.com',
    storageBucket: 'hoofhub-4f4a7.firebasestorage.app',
  );

}