// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBIjGlOzK8MRIiFMwrMNZBDJ0nefjTbL6o',
    appId: '1:790831491577:web:f9911818d0818147f77528',
    messagingSenderId: '790831491577',
    projectId: 'hoofhub-70999',
    authDomain: 'hoofhub-70999.firebaseapp.com',
    storageBucket: 'hoofhub-70999.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAaJY3nRuxs2FAnURgbqqto7R-TaGr5fXU',
    appId: '1:790831491577:android:829fdb4a7996ecbcf77528',
    messagingSenderId: '790831491577',
    projectId: 'hoofhub-70999',
    storageBucket: 'hoofhub-70999.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDa33AJLp_4OmN1MMC3FcjzMMSKSF6EWGs',
    appId: '1:790831491577:ios:6cb2d33297ce198ff77528',
    messagingSenderId: '790831491577',
    projectId: 'hoofhub-70999',
    storageBucket: 'hoofhub-70999.firebasestorage.app',
    iosBundleId: 'com.example.frontend',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDa33AJLp_4OmN1MMC3FcjzMMSKSF6EWGs',
    appId: '1:790831491577:ios:6cb2d33297ce198ff77528',
    messagingSenderId: '790831491577',
    projectId: 'hoofhub-70999',
    storageBucket: 'hoofhub-70999.firebasestorage.app',
    iosBundleId: 'com.example.frontend',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBIjGlOzK8MRIiFMwrMNZBDJ0nefjTbL6o',
    appId: '1:790831491577:web:bb10c74937f3450bf77528',
    messagingSenderId: '790831491577',
    projectId: 'hoofhub-70999',
    authDomain: 'hoofhub-70999.firebaseapp.com',
    storageBucket: 'hoofhub-70999.firebasestorage.app',
  );
}
